version: '3.8'
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - "8000:8000"
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb
  app:
    container_name: message-api
    build: .
    ports:
      - "3000:3000"
    environment:
      - AWS_ACCESS_KEY_ID=user
      - AWS_SECRET_ACCESS_KEY=pass
      - AWS_REGION=us-west-2
      - DYNAMODB_ENDPOINT=http://localhost:8000
    depends_on:
      - dynamodb
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
